<a href="https://colab.research.google.com/github/touhid0503/NumPy/blob/main/numpy_02_02_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [170]:
import numpy as np

In [171]:
arr=np.array([1,2,3])
r1=np.repeat(arr,4,axis=0)
print(arr)
print(r1)

[1 2 3]
[1 1 1 1 2 2 2 2 3 3 3 3]


In [172]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(type(arr))

1
(3,)
3
int64
8
24
<class 'numpy.ndarray'>


In [173]:
print(r1.ndim)
print(r1.shape)
print(r1.size)
print(r1.dtype)
print(r1.itemsize)
print(r1.nbytes)
print(type(r1))

1
(12,)
12
int64
8
96
<class 'numpy.ndarray'>


In [174]:
arr2=np.array([[1,2,3]])
r2=np.repeat(arr2,4,axis=0)
print(arr2)
print(r2)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [175]:
print(r2.ndim)
print(r2.shape)
print(r2.size)
print(r2.dtype)
print(r2.itemsize)
print(r2.nbytes)
print(type(r2))

2
(4, 3)
12
int64
8
96
<class 'numpy.ndarray'>


In [176]:
arr2[0]

array([1, 2, 3])

In [177]:
arr2[0][1]

np.int64(2)

In [178]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.nbytes)
print(type(arr2))

2
(1, 3)
3
int64
8
24
<class 'numpy.ndarray'>


In [179]:
arr21=np.array([[1,2,3]])
r21=np.repeat(arr21,4,axis=1)
print(arr21)
print(r21)

[[1 2 3]]
[[1 1 1 1 2 2 2 2 3 3 3 3]]


In [180]:
print(r21.ndim)
print(r21.shape)
print(r21.size)
print(r21.dtype)
print(r21.itemsize)
print(r21.nbytes)
print(type(r21))

2
(1, 12)
12
int64
8
96
<class 'numpy.ndarray'>


In [181]:
print(arr21.ndim)
print(arr21.shape)
print(arr21.size)
print(arr21.dtype)
print(arr21.itemsize)
print(arr21.nbytes)
print(type(arr21))

2
(1, 3)
3
int64
8
24
<class 'numpy.ndarray'>


In [182]:
arr3=np.array([[[1,2,3]]])
r3=np.repeat(arr3,4,axis=0)
print(arr3)
print(r3)

[[[1 2 3]]]
[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]]


In [183]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)
print(arr3.nbytes)
print(type(arr3))

3
(1, 1, 3)
3
int64
8
24
<class 'numpy.ndarray'>


In [184]:
print(r3.ndim)
print(r3.shape)
print(r3.size)
print(r3.dtype)
print(r3.itemsize)
print(r3.nbytes)
print(type(r3))

3
(4, 1, 3)
12
int64
8
96
<class 'numpy.ndarray'>


In [185]:
arr3=np.array([[[1,2,3]]])
r3=np.repeat(arr3,4,axis=1)
print(arr3)
print(r3)

[[[1 2 3]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]


In [186]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)
print(arr3.nbytes)
print(type(arr3))

3
(1, 1, 3)
3
int64
8
24
<class 'numpy.ndarray'>


In [187]:
print(r3.ndim)
print(r3.shape)
print(r3.size)
print(r3.dtype)
print(r3.itemsize)
print(r3.nbytes)
print(type(r3))

3
(1, 4, 3)
12
int64
8
96
<class 'numpy.ndarray'>


In [188]:
arr3=np.array([[[1,2,3]]])
r3=np.repeat(arr3,4,axis=2)
print(arr3)
print(r3)

[[[1 2 3]]]
[[[1 1 1 1 2 2 2 2 3 3 3 3]]]


In [189]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)
print(arr3.nbytes)
print(type(arr3))

3
(1, 1, 3)
3
int64
8
24
<class 'numpy.ndarray'>


In [190]:
print(r3.ndim)
print(r3.shape)
print(r3.size)
print(r3.dtype)
print(r3.itemsize)
print(r3.nbytes)
print(type(r3))

3
(1, 1, 12)
12
int64
8
96
<class 'numpy.ndarray'>


In [191]:
arr3d=np.random.rand(3,2,4)
print(arr3d)

[[[0.38214542 0.27027934 0.07114267 0.73504857]
  [0.15151234 0.54204936 0.40904713 0.83174846]]

 [[0.92159728 0.41329045 0.39186057 0.0589876 ]
  [0.89042079 0.88640455 0.31119755 0.44755658]]

 [[0.2516332  0.94126601 0.6181088  0.23306557]
  [0.58232726 0.62332851 0.39515602 0.82766055]]]


In [192]:
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.size)
print(arr3d.dtype)
print(arr3d.itemsize)
print(arr3d.nbytes)
print(type(arr3d))

3
(3, 2, 4)
24
float64
8
192
<class 'numpy.ndarray'>


In [193]:
r3d=np.repeat(arr3d,2,axis=0)
print(r3d)

[[[0.38214542 0.27027934 0.07114267 0.73504857]
  [0.15151234 0.54204936 0.40904713 0.83174846]]

 [[0.38214542 0.27027934 0.07114267 0.73504857]
  [0.15151234 0.54204936 0.40904713 0.83174846]]

 [[0.92159728 0.41329045 0.39186057 0.0589876 ]
  [0.89042079 0.88640455 0.31119755 0.44755658]]

 [[0.92159728 0.41329045 0.39186057 0.0589876 ]
  [0.89042079 0.88640455 0.31119755 0.44755658]]

 [[0.2516332  0.94126601 0.6181088  0.23306557]
  [0.58232726 0.62332851 0.39515602 0.82766055]]

 [[0.2516332  0.94126601 0.6181088  0.23306557]
  [0.58232726 0.62332851 0.39515602 0.82766055]]]


In [194]:
r3d=np.repeat(arr3d,2,axis=1)
print(r3d)

[[[0.38214542 0.27027934 0.07114267 0.73504857]
  [0.38214542 0.27027934 0.07114267 0.73504857]
  [0.15151234 0.54204936 0.40904713 0.83174846]
  [0.15151234 0.54204936 0.40904713 0.83174846]]

 [[0.92159728 0.41329045 0.39186057 0.0589876 ]
  [0.92159728 0.41329045 0.39186057 0.0589876 ]
  [0.89042079 0.88640455 0.31119755 0.44755658]
  [0.89042079 0.88640455 0.31119755 0.44755658]]

 [[0.2516332  0.94126601 0.6181088  0.23306557]
  [0.2516332  0.94126601 0.6181088  0.23306557]
  [0.58232726 0.62332851 0.39515602 0.82766055]
  [0.58232726 0.62332851 0.39515602 0.82766055]]]


In [195]:
r3d=np.repeat(arr3d,2,axis=2)
print(r3d)

[[[0.38214542 0.38214542 0.27027934 0.27027934 0.07114267 0.07114267
   0.73504857 0.73504857]
  [0.15151234 0.15151234 0.54204936 0.54204936 0.40904713 0.40904713
   0.83174846 0.83174846]]

 [[0.92159728 0.92159728 0.41329045 0.41329045 0.39186057 0.39186057
   0.0589876  0.0589876 ]
  [0.89042079 0.89042079 0.88640455 0.88640455 0.31119755 0.31119755
   0.44755658 0.44755658]]

 [[0.2516332  0.2516332  0.94126601 0.94126601 0.6181088  0.6181088
   0.23306557 0.23306557]
  [0.58232726 0.58232726 0.62332851 0.62332851 0.39515602 0.39515602
   0.82766055 0.82766055]]]


In [196]:
problem1=np.ones((5,5))
problem1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [197]:
print(problem1.ndim)
print(problem1.shape)
print(problem1.size)
print(problem1.dtype)
print(problem1.itemsize)
print(problem1.nbytes)
print(type(problem1))

2
(5, 5)
25
float64
8
200
<class 'numpy.ndarray'>


In [198]:
zero1=np.zeros((3,3))
zero1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [199]:
zero1[1,1]=9
zero1

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [200]:
problem1[1:4,1:4]=zero1

In [201]:
problem1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [202]:
print(problem1.ndim)
print(problem1.shape)
print(problem1.size)
print(problem1.dtype)
print(problem1.itemsize)
print(problem1.nbytes)
print(type(problem1))

2
(5, 5)
25
float64
8
200
<class 'numpy.ndarray'>


In [203]:
a=np.array([[1,2,3],[3,2,1]])
b=np.array([[4,5],[5,4],[4,5]])

In [204]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(type(a))
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)
print(type(b))

2
(2, 3)
6
int64
8
48
<class 'numpy.ndarray'>
2
(3, 2)
6
int64
8
48
<class 'numpy.ndarray'>


In [205]:
#a*b
mul1=np.matmul(a,b)
mul1

array([[26, 28],
       [26, 28]])

In [206]:
print(mul1.ndim)
print(mul1.shape)
print(mul1.size)
print(mul1.dtype)
print(mul1.itemsize)
print(mul1.nbytes)
print(type(mul1))

2
(2, 2)
4
int64
8
32
<class 'numpy.ndarray'>


In [207]:
c=np.linalg.det(np.identity(3))
print(c)

1.0


In [208]:
c=np.linalg.det(np.identity(5))
print(c)

1.0


In [209]:
stat=np.array([[1,2,3],[4,5,6]])
stat

array([[1, 2, 3],
       [4, 5, 6]])

In [210]:
np.min(stat)

np.int64(1)

In [211]:
np.max(stat)

np.int64(6)

In [212]:
np.min(stat,axis=0)

array([1, 2, 3])

In [213]:
np.max(stat,axis=0)

array([4, 5, 6])

In [214]:
np.min(stat,axis=1)

array([1, 4])

In [215]:
np.max(stat,axis=1)

array([3, 6])

In [216]:
np.sum(stat)

np.int64(21)

In [217]:
np.sum(stat,axis=0)

array([5, 7, 9])

In [218]:
np.sum(stat,axis=1)

array([ 6, 15])

In [219]:
file1=np.genfromtxt('/content/number.txt',delimiter=',',dtype='int64')

In [220]:
file1

array([ 1,  2, 10, 21,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [221]:
print(file1.ndim)
print(file1.shape)
print(file1.size)
print(file1.dtype)
print(file1.itemsize)
print(file1.nbytes)
print(type(file1))

1
(14,)
14
int64
8
112
<class 'numpy.ndarray'>


In [222]:
file1.astype('float64')

array([ 1.,  2., 10., 21.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,
       10.])

In [223]:
np.any(file1>10,axis=0)

np.True_

In [224]:
np.all(file1>10,axis=0)

np.False_

In [226]:
(file1>5) & (file1<20)

array([False, False,  True, False, False, False, False, False, False,
        True,  True,  True,  True,  True])

In [227]:
~(file1>5) & (file1<20)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
       False, False, False, False, False])

In [231]:
file1[(file1>5) & (file1<30)]

array([10, 21,  6,  7,  8,  9, 10])