<a href="https://colab.research.google.com/github/touhid0503/NumPy/blob/main/numpy_01_02_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
z=np.zeros(2)

In [21]:
z

array([0., 0.])

In [18]:
z[0]

np.float64(0.0)

In [32]:
z[0:1]

array([0.])

In [22]:
z1=np.zeros((2,3,2),dtype='int64')
print(z1)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]


In [33]:
z1[0]

array([[0, 0],
       [0, 0],
       [0, 0]])

In [34]:
z1[1,0]

array([0, 0])

In [35]:
z1[1,1,0]

np.int64(0)

In [42]:
z1[::1]

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [43]:
z1[:1]

array([[[0, 0],
        [0, 0],
        [0, 0]]])

In [23]:
print(z1.ndim)
print(z1.shape)
print(z1.size)
print(z1.dtype)
print(z1.itemsize)
print(z1.nbytes)
print(type(z1))

3
(2, 3, 2)
12
int64
8
96
<class 'numpy.ndarray'>


In [24]:
o=np.ones(2)
print(o)

[1. 1.]


In [44]:
o[:1]

array([1.])

In [25]:
o1=np.ones((2,3,2))
print(o1)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [52]:
o1[1:]

array([[[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [53]:
o1[1][1]

array([1., 1.])

In [54]:
o1[1][1][1]

np.float64(1.0)

In [49]:
print(o1.ndim)
print(o1.shape)
print(o1.size)
print(o1.dtype)
print(o1.itemsize)
print(o1.nbytes)
print(type(o1))

3
(2, 3, 2)
12
float64
8
96
<class 'numpy.ndarray'>


In [46]:
o2=np.hstack(o1)
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
o2[-1]

array([1., 1., 1., 1.])

In [57]:
o21=o2.copy()
print(o21)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [58]:
o21[1][1]=5
print(o21)

[[1. 1. 1. 1.]
 [1. 5. 1. 1.]
 [1. 1. 1. 1.]]


In [59]:
o2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
print(o2.ndim)
print(o2.shape)
print(o2.size)
print(o2.dtype)
print(o2.itemsize)
print(o2.nbytes)
print(type(o2))

2
(3, 4)
12
float64
8
96
<class 'numpy.ndarray'>


In [47]:
o3=np.vstack(o1)
o3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [60]:
o31=o3.copy()
print(o31)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [61]:
o31[4][0]=4
print(o31)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [4. 1.]
 [1. 1.]]


In [62]:
print(o3)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [50]:
print(o3.ndim)
print(o3.shape)
print(o3.size)
print(o3.dtype)
print(o3.itemsize)
print(o3.nbytes)
print(type(o3))

2
(6, 2)
12
float64
8
96
<class 'numpy.ndarray'>


In [27]:
f=np.full((2,2),7)
print(f)

[[7 7]
 [7 7]]


In [28]:
print(f.ndim)
print(f.shape)
print(f.size)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)
print(type(f))

2
(2, 2)
4
int64
8
32
<class 'numpy.ndarray'>


In [29]:
f1=np.full_like(z1,4)
print(f1)

[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]


In [30]:
print(f1.ndim)
print(f1.shape)
print(f1.size)
print(f1.dtype)
print(f1.itemsize)
print(f1.nbytes)
print(type(f1))

3
(2, 3, 2)
12
int64
8
96
<class 'numpy.ndarray'>


In [64]:
f1.shape

(2, 3, 2)

In [65]:
f2=np.full_like(z1,5)
print(f2)

[[[5 5]
  [5 5]
  [5 5]]

 [[5 5]
  [5 5]
  [5 5]]]


In [67]:
f3=np.full(z1.shape,6)
print(f3)

[[[6 6]
  [6 6]
  [6 6]]

 [[6 6]
  [6 6]
  [6 6]]]


In [68]:
print(f2.ndim)
print(f2.shape)
print(f2.size)
print(f2.dtype)
print(f2.itemsize)
print(f2.nbytes)
print(type(f2))

3
(2, 3, 2)
12
int64
8
96
<class 'numpy.ndarray'>


In [69]:
print(f3.ndim)
print(f3.shape)
print(f3.size)
print(f3.dtype)
print(f3.itemsize)
print(f3.nbytes)
print(type(f3))

3
(2, 3, 2)
12
int64
8
96
<class 'numpy.ndarray'>


In [71]:
r=np.random.rand(4,2)
print(r)

[[0.49149187 0.53717983]
 [0.98200006 0.58839152]
 [0.29344687 0.87667588]
 [0.5493937  0.76947296]]


In [74]:
r1=np.random.random_sample(z1.shape)
r1

array([[[0.91944436, 0.03555985],
        [0.83341974, 0.23565312],
        [0.33467449, 0.64965559]],

       [[0.29139864, 0.71481491],
        [0.45477777, 0.4382366 ],
        [0.9164603 , 0.26185195]]])

In [76]:
print(r1.ndim)
print(r1.shape)
print(r1.size)
print(r1.dtype)
print(r1.itemsize)
print(r1.nbytes)
print(type(r1))

3
(2, 3, 2)
12
float64
8
96
<class 'numpy.ndarray'>


In [78]:
i=np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
print(i.ndim)
print(i.shape)
print(i.size)
print(i.dtype)
print(i.itemsize)
print(i.nbytes)
print(type(i))

2
(5, 5)
25
float64
8
200
<class 'numpy.ndarray'>
