<a href="https://colab.research.google.com/github/touhid0503/NumPy/blob/main/numpy_24_01_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#libraries

In [145]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Slicing

In [146]:
a=np.round(10*np.random.rand(5,4))

In [147]:
a

array([[10.,  2.,  4.,  2.],
       [ 9.,  7.,  3.,  8.],
       [10.,  6.,  3.,  7.],
       [ 4.,  8.,  1.,  0.],
       [ 2.,  1.,  2.,  0.]])

In [148]:
print(a[1,1])

7.0


In [149]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.shape[0])

<class 'numpy.ndarray'>
2
float64
160
5


In [150]:
a[1,:]

array([9., 7., 3., 8.])

In [151]:
a[0:2]

array([[10.,  2.,  4.,  2.],
       [ 9.,  7.,  3.,  8.]])

In [152]:
a[1:2]

array([[9., 7., 3., 8.]])

In [153]:
a[:2]

array([[10.,  2.,  4.,  2.],
       [ 9.,  7.,  3.,  8.]])

In [154]:
a[2:]

array([[10.,  6.,  3.,  7.],
       [ 4.,  8.,  1.,  0.],
       [ 2.,  1.,  2.,  0.]])

In [155]:
a[1,0:3]

array([9., 7., 3.])

In [156]:
a[:,2]

array([4., 3., 3., 1., 2.])

In [157]:
a[2,:]

array([10.,  6.,  3.,  7.])

In [158]:
a[1:2,2:3]

array([[3.]])

In [159]:
a.T

array([[10.,  9., 10.,  4.,  2.],
       [ 2.,  7.,  6.,  8.,  1.],
       [ 4.,  3.,  3.,  1.,  2.],
       [ 2.,  8.,  7.,  0.,  0.]])

In [160]:
import numpy.linalg as la

In [161]:
a=np.random.rand(3,3)
print(la.inv(a))

[[ -1.98853091   3.87089215   0.70331985]
 [  5.7147026  -11.70007511   1.12497038]
 [ -3.17432844   9.74319455  -2.12856364]]


In [162]:
a

array([[0.75066331, 0.81249238, 0.67744569],
       [0.46261621, 0.34806422, 0.33681356],
       [0.99809459, 0.38154355, 0.06164012]])

In [163]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.shape[1])

<class 'numpy.ndarray'>
2
float64
72
3


In [164]:
a.sort(axis=0)
a

array([[0.46261621, 0.34806422, 0.06164012],
       [0.75066331, 0.38154355, 0.33681356],
       [0.99809459, 0.81249238, 0.67744569]])

In [165]:
a.sort(axis=1)
a

array([[0.06164012, 0.34806422, 0.46261621],
       [0.33681356, 0.38154355, 0.75066331],
       [0.67744569, 0.81249238, 0.99809459]])

#indexing

In [166]:
a[[1]]

array([[0.33681356, 0.38154355, 0.75066331]])

In [167]:
a[1]

array([0.33681356, 0.38154355, 0.75066331])

In [168]:

a = np.array([10, 20, 30, 40])

# Normal indexing
x = a[1]
print("a[1]:", x)
print("type:", type(x))
print("shape:", x.shape)
print(x.ndim)
print(x.dtype)
print(x.nbytes)
print(x.size)

# Fancy indexing
y = a[[0,2,3]]
print("\na[[1]]:", y)
print("type:", type(y))
print("shape:", y.shape)
print(y.ndim)
print(y.dtype)
print(y.nbytes)
print(y.shape[0])
print(len(y))
print(y.size)

a[1]: 20
type: <class 'numpy.int64'>
shape: ()
0
int64
8
1

a[[1]]: [10 30 40]
type: <class 'numpy.ndarray'>
shape: (3,)
1
int64
24
3
3
3


In [169]:
a[[True,True,False,True]]

array([10, 20, 40])

In [170]:
a[a<30]

array([10, 20])

In [171]:
a[(a > 10) & (a < 40)]

array([20, 30])

#copy vs view

In [172]:
a=np.array([1,2,3,4])
b=a.copy()
b[0]=10
print(a)
print(b)

[1 2 3 4]
[10  2  3  4]


In [173]:
b[[0,2,3]]=15
print(b)
print(a)

[15  2 15 15]
[1 2 3 4]


#broadcasting

In [174]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [175]:
c=a.copy()
c+1

array([2, 3, 4])

In [176]:
a

array([1, 2, 3])

In [177]:
b=np.arange(2).reshape(2,1)
b

array([[0],
       [1]])

In [178]:
a+b

array([[1, 2, 3],
       [2, 3, 4]])

In [179]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.hstack((a, b))
d=np.vstack((a,b))
print(c)
print(c.shape)
print(d)
print(d.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


#Seed : ufuncs

In [181]:
B=np.random.rand(1000000)
%timeit B.sum()
%timeit np.sum(B)

465 µs ± 128 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
380 µs ± 90.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [182]:
def mysum(g):
  s=0
  for x in g:
      s+=x
  return s

In [183]:
%timeit mysum(B)

135 ms ± 42.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
